/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ebill;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author komal
 */
public class electricity extends javax.swing.JFrame {

    /**
     * Creates new form electricity
     */
    public electricity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcid = new javax.swing.JPanel();
        txtCid = new javax.swing.JLabel();
        txtcname = new javax.swing.JLabel();
        txtunit = new javax.swing.JLabel();
        txtcidd = new javax.swing.JTextField();
        txtCname = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtcal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();
        txtPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Electricity Billing System");

        txtCid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCid.setText("Customer ID");

        txtcname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcname.setText("Customer Name");

        txtunit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtunit.setText("Unit");

        txtcal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcal.setText("Cal");
        txtcal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalActionPerformed(evt);
            }
        });

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        txtPrint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrint.setText("Print");
        txtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtcidLayout = new javax.swing.GroupLayout(txtcid);
        txtcid.setLayout(txtcidLayout);
        txtcidLayout.setHorizontalGroup(
            txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtcidLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcal)
                    .addGroup(txtcidLayout.createSequentialGroup()
                        .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCid)
                            .addComponent(txtcname)
                            .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcidd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtcidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrint)
                .addGap(109, 109, 109))
        );
        txtcidLayout.setVerticalGroup(
            txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtcidLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCid)
                    .addComponent(txtcidd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcname)
                    .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(txtcidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtunit)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(txtcal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtcidLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrint)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        String cid;
        double charge,gramount;
    int count;
    
    public void print(){
        String cid=txtcidd.getText();
         String cname=txtCname.getText();
         String unit=txtUnit.getText();
         txtprint.setText(txtprint.getText()+"\n");
           txtprint.setText(txtprint.getText() + " Electricity Billing System" + "\n");
             txtprint.setText(txtprint.getText()+"\n");
               txtprint.setText(txtprint.getText() + "Customer Id : = "+ cid +"\n");
                   txtprint.setText(txtprint.getText() + "Customer Name: = "+ cname +"\n");
                       txtprint.setText(txtprint.getText() + "Unit: = "+ unit +"\n");
                           txtprint.setText(txtprint.getText() + "Amount: = "+ gramount +"\n");
                           txtprint.setText(txtprint.getText()+"Thank you Visit again");
    }

    private void txtcalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalActionPerformed
        cid = txtcidd.getText();
      count=Integer.parseInt(txtUnit.getText());
        if(count <500){
           charge=1.00; 
        }
          else if(count <500 && count <600){
           charge=1.80; 
        }
            else if(count <600 && count <800){
           charge=2.80; 
        }
            else{
                charge=3.00;
            }
        gramount =charge * count;
        print();
    }//GEN-LAST:event_txtcalActionPerformed

    private void txtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintActionPerformed
        try {
            // TODO add your handling code here:
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(electricity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPrintActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new electricity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCid;
    private javax.swing.JTextField txtCname;
    private javax.swing.JButton txtPrint;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JButton txtcal;
    private javax.swing.JPanel txtcid;
    private javax.swing.JTextField txtcidd;
    private javax.swing.JLabel txtcname;
    private javax.swing.JTextArea txtprint;
    private javax.swing.JLabel txtunit;
    // End of variables declaration//GEN-END:variables
}
